### ISSUE TITLE
Script ideas.

### ISSUE THREAD

**Issue by starvald** [ancalentari/twitch-stream-recorder#1]
Hi, this is mosty a thanks for the new recorder script. :)

possibly add being able to disable ffmpeg conversion, never had a problem playing the recorded stream and if the stream dies i want to start recording again as quickly as possible not wait until ffmpeg finishes. misnamed ffmpeg for now.

thanks again.

**Comment by ancalentari** [comment]
Hey, noted. Maybe at the end of the week when I'm not busy, but I can't promise anything ;)
Have a good day

**Comment by starvald** [comment]
many thanks.
