### ISSUE TITLE
--twitch-oauth-token argument was removed in Streamlink 2.0.0

### ISSUE THREAD

**Issue by gladiatortoise** [ancalentari/twitch-stream-recorder#10]
Changelog of streamlink 2.0.0:
![image](https://user-images.githubusercontent.com/5674770/103954245-778c9b80-514c-11eb-99c0-7d951aa7f988.png)

Argument --twitch-ouath-token used here:
https://github.com/ancalentari/twitch-stream-recorder/blob/fd74d8eb175ec852e1df12a275be395ce5ac4e2e/twitch-recorder.py#L153

Causes a fatal error 👎 The solution would be to just remove the argument altogether. I don't know what purpose it served in the first place

**Comment by Stefomat** [comment]
Maybe it's just my missing knowledge about how the python script and streamlink connect to twitch exactly, but why do we need to authenticate in the first place? Why is a registration and token from https://dev.twitch.tv/console/apps neccessary? AFAIK, youtube-dl can also grab and download livestreams from twitch, without token. How is it different from this project?

**Comment by gladiatortoise** [comment]
> Maybe it's just my missing knowledge about how the python script and streamlink connect to twitch exactly, but why do we need to authenticate in the first place? Why is a registration and token from https://dev.twitch.tv/console/apps neccessary? AFAIK, youtube-dl can also grab and download livestreams from twitch, without token. How is it different from this project?

In this script it's used to poll target channel's online status. In streamlink user provided oauth was "disabled" already in April (1.4.0), and I'm not 100% sure what purpose it served

**Comment by DerSani1988** [comment]
Only remove following parameters from code and it'll work:
`"--twitch-oauth-token", self.access_token,`
