### ISSUE TITLE
Record Multiple Streams at once

### ISSUE THREAD

**Issue by MexTrx** [ancalentari/twitch-stream-recorder#15]
Is it possible to allow this to record multiple streams at once?

**Comment by DravenTec** [comment]
I made an extra file for each stream which runs and records permanently. But you can also just start the whole thing with **--username** (_python3.8 twitch-recorder.py --username STREAMERNAME_) and specify the desired stream. 
It is not intended to record multiple streams with one file. 
So just create a separate file for each stream and run it with systemd or screen.

**Comment by MexTrx** [comment]
Gotcha. Seen a few that run multiple streams but wasn't stable as they would cut out after time.
