### ISSUE TITLE
Is there anyway to avoid 720p, but only start download when it's 1080p?

### ISSUE THREAD

**Issue by poundarg** [ancalentari/twitch-stream-recorder#20]
Hi, I've been using this thing about a half year now, and I noticed that 
'when the stream starts, it begins with 720p, and then goes up to 1080p.'

It feels really bad when I finds my files were downloaded in 720p.
Even if I put the refresh rate on 5 minutes, there are some unlucky (or should I say I was extremely lucky that refresh timing and the beginning of streaming was on the exact time) moments.

So I'm wondering **If there's anyway not to start downloading when the best output is 720p, make the program waits for a few moments, and then download when 1080p is available?**

Thanks for your help in advance! I totally love this! It saves my live as an editor several times.

**Comment by Seb3thehacker** [comment]
Weird, I haven't ever had that issue. Is "best" quality set in the config? Also did you try downloading the program again and reconfiguring it?

**Comment by poundarg** [comment]
> 

`        # user configuration
        self.username = config.username
        self.quality = "best"
`
Yes it's definitely on "best" quality.
What I was wondering is that 'when the stream just started, the best output is at 720p for a few moments.' so, I know that the real 'best' output is always 1080p.

So maybe is there's any ways to make the program not starts downloading when it's at 720p, and make it wait until it re-recognize the available output is at 1080p?

I don't really think it's a matter of redownload and re-configure the program

**Comment by DravenTec** [comment]
If the value self.quality is fixed, the recording should only take place then. 
self.quality = "1080p" 
Or pass the desired value when calling it.
twitch-recorder.py STREAMURL -q 1080p

However, should the stream for some reason only take place in 720p or another resolution because, for example, 
the resolution for a game was reduced, nothing is recorded.

**Comment by poundarg** [comment]
So, I tested the program with the quality on "1080p"
Apparently, when the stream is available with 60fps, you have to write "1080p60"

So yeah, It worked! Thank  you so much!
