### ISSUE TITLE
This repo kinda looks unmaintained; better twitch stream recorder :)

### ISSUE THREAD

**Issue by Avnsx** [ancalentari/twitch-stream-recorder#29]
Made a similar twitch-recorder if anyone wants to use it: https://github.com/Avnsx/twitch-stream

This repo is unmaintained and also introducing the usage of twitch API as shown in this repo is kinda bothersome, so mine is way easier to set up and use. Just trying to help! :)

**Comment by dailypush** [comment]
not bad but looks like your missing the checks for streamers.  I like the asynico.. should be added to this script too.
My use case is dedicating a raspberry pi zero to automatically to record Twitch DJs (since vods typically rip out the music)

There are definitely a few different packages out there that do a better job then this script.. but it was the first one I found that worked pretty straight forward.  Maybe ask if you can take over as maintainer of repo or Fork

**Comment by tekkitan** [comment]
May be unmaintained but using the API with authentication means you can record streams without ads. There is no authentication with your method which means you will get all the ads Twitch throws at you.

**Comment by Avnsx** [comment]
> May be unmaintained but using the API with authentication means you can record streams without ads. There is no authentication with your method which means you will get all the ads Twitch throws at you.

Aren't you getting the ads regardless of authentication or not? I mean if I am logged in, in my browser and watching a stream I will still get ads, why would it be any different in an authenticated session over the API lol

Also over streamlink, in my method you only get that banner that says you're watching through 3rd party app or whatever, which lasts for a couple seconds, it's not like u will get 5 minutes+ ad wall

**Comment by tekkitan** [comment]
I think I have gotten around it by both purchasing Twitch Turbo as well as modifying the code to provide my auth token. Seems to have done the trick.

**Comment by Avnsx** [comment]
> I think I have gotten around it by both purchasing Twitch Turbo as well as modifying the code to provide my auth token. Seems to have done the trick.

Ok I guess if you're a hardcore no-life that sits all day inside, to the point where that 30 second banner every hour, forces you to buy twitch turbo (9$ / month) to avoid watching ads all day long, it might make sense

didn't really think that far lol
but that's like 1% of the people and I couldn't care less tbh

**Comment by tekkitan** [comment]
> > I think I have gotten around it by both purchasing Twitch Turbo as well as modifying the code to provide my auth token. Seems to have done the trick.
> 
> Ok I guess if you're a hardcore no-life that sits all day inside, to the point where that 30 second banner every hour, forces you to buy twitch turbo (9$ / month) to avoid watching ads all day long, it might make sense
> 
> didn't really think that far lol but that's like 1% of the people and I couldn't care less tbh

If you think I need to be a hardcore no-life that sits inside all day to make changes to a couple of lines of code and spend a whopping $8/month on something, you're fucking stupid. I record VODs to upload to Youtube for a big streamer. Having ads in those videos would be almost as stupid as your comment.

Enjoy making subpar scripts that are worse than the unmaintained ones.

**Comment by Avnsx** [comment]
> I record VODs to upload to Youtube for a big streamer. Having ads in those videos would be almost as stupid as your comment.

There we go, caught another incel slippin' kekw
my mans ain't got nothing better to do then record some big twitch thots streams for her. Let me guess it's a half-naked woman from Just Chatting section, whose too incompetent to select record in OBS to save as video simultaneously 🤣

I love how quickly you got offended too, it just proves my hypotehsis even more, kinda funny to me. whatever you respond now, keep coping in your lil basement bud

**Comment by tekkitan** [comment]
> > I record VODs to upload to Youtube for a big streamer. Having ads in those videos would be almost as stupid as your comment.
> 
> There we go, caught another incel slippin' kekw my mans ain't got nothing better to do then record some big twitch thots streams for her. Let me guess it's a half-naked woman from Just Chatting section, whose too incompetent to select record in OBS to save as video simultaneously 🤣
> 
> I love how quickly you got offended too, it just proves my hypothesis even more, kinda funny to me. whatever you respond now, keep coping in your lil basement bud

Nope. You're wrong. Also you're the one that got offended kiddo because you couldn't take criticism about your subpar script you decided to advertise on someone else's project. Sorry you couldn't figure out how to work with streamlink and the Twitch API. Maybe go back to programming school. Your comments have been reported to Github so enjoy while you can.

**Comment by Avnsx** [comment]
> Your comments have been reported to Github so enjoy while you can.

HAHAHHAHA I knew it, average twitch mod. Not feeling too well, when that ban user from chat button isn't on here huh 🤣

I hope you feel better about your lifes circumstances now that you reported me to github, have a great one buddy
