### ISSUE TITLE
ModuleNotFoundError: No module named 'config'

### ISSUE THREAD

**Issue by ConnerGinn** [ancalentari/twitch-stream-recorder#5]
Windows 10 1903
Streamlink 1.7.0
Elevated command prompt

Hi, there is a strong chance I am doing this incorrectly, but please help me understand:

I have created the config.py file in the same directory as twitch-recorder.py on my D: drive. I have filled the information as per the readme, and I have installed python and the request module. I have navigated to the directory in the command prompt.

However, when I run the command `python twitch-recorder.py` I receive the following error: 

`Traceback (most recent call last):`
`  File "twitch-recorder.py", line 13, in <module>`
`    import config`
`ModuleNotFoundError: No module named 'config'`

I have triple checked the readme on both github and in the file, and I feel as if I have followed the instructions to a tee. Any help would be massively appreciated.

**Comment by starvald** [comment]
try running it with different python versions, i use  'python3 twitch-recorder.py"

**Comment by ConnerGinn** [comment]
> 
> 
> try running it with different python versions, i use 'python3 twitch-recorder.py"

This worked, thanks so much Starvald!
